@startuml
title Use Case Optimize Self Consumption \n Existing: LoadAgent, HomeStorage, PV, EV \n Missing: -
participant GridAgent
participant HEMSAgent
participant LoadAgent
participant PVAgent
participant HomeStorageAgent
participant EvcsAgent1
participant EV
/'group to be discussed
    HEMSAgent -> HEMSAgent: a. Charge EV before HomeStorage \n b. first HomeStorage then EV \n c. both at same time?
        end '/
group init
    activate GridAgent
    GridAgent -> HEMSAgent: create()
    activate HEMSAgent
    HEMSAgent -> LoadAgent: create()
    activate LoadAgent
    HEMSAgent -> PVAgent: create()
    activate PVAgent
    HEMSAgent -> HomeStorageAgent: create(Volume, RatedPower, SoC)
    activate HomeStorageAgent
    HEMSAgent -> EvcsAgent1: create (RatedPower)
    activate EvcsAgent1
    end
group #LightGrey firstTick
    GridAgent -> HEMSAgent: request PowerDemand
    HEMSAgent -> LoadAgent: get PowerDemand
    LoadAgent -> HEMSAgent: PowerDemand
    HEMSAgent -> PVAgent: get PVInput
    PVAgent -> HEMSAgent: PVInput
    HEMSAgent -> HomeStorageAgent: get SoC, get RatedPowerHomeStorage
    HomeStorageAgent -> HEMSAgent:  SoC, RatedPowerHomeStorage
    HEMSAgent -> EvcsAgent1: get SoC, get PowerDemand
    alt#Gold no EV
    HEMSAgent -> EvcsAgent1: get PowerDemand
    EvcsAgent1 -> HEMSAgent: PowerDemandEvcsAgent1 = 0
    else EV
    activate EV
        HEMSAgent -> EvcsAgent1: get PowerDemand
        EvcsAgent1 -> EV: get SoC, get DemandEV, RatedPowerEV
        EV -> EvcsAgent1: SoC, DemandEV, RatedPowerEV
        EvcsAgent1 -> HEMSAgent: SoC, PowerDemandEvcs, RatedPowerCharging = min [RatedPowerEvcs  | RatedPowerEV]
        /' If there is Demand of the EV to be charged, this will be fulfilled at max Power
        '/
        alt#Gold PowerDemandEvcsAgent1 > 0 -> ChargeEV
            HEMSAgent -> EvcsAgent1: PowerDemandEvcsAgent1 = RatedPowerCharging
            EvcsAgent1 -> EV: RatedPowerCharging
            HEMSAgent -> HomeStorageAgent: PowerDemandHomeStorage = min [PVInput - PowerDemandLoadAgent - PowerDemandEvcsAgent1 | RatedPowerCharging]
            HEMSAgent -> GridAgent: PowerDemandGrid = PowerDemandLoadAgent - PVInput + PowerDemandHomeStorage + PowerDemandEvcsAgent1
        /' If there is NO Demand of the EV to be charged,
            if there is more PV then Demand of LoadAgent, EV will be charged with min of PV - DemandLoadAgent or with RatedPowerCharging (Delta to Homestorage or then Feed-in )
            if there is less PV then Demand of LoadAgent, HomeStorage will be uncharged, if this isn't enough to avoid taking power from Grid, EV will be uncharged till SoC !=< 60%
            '/
        else PowerDemandEvcsAgent1 = 0
            alt#Gold PVInput - PowerDemandLoadAgent > 0 /' Soc !< 1 '/
            HEMSAgent -> EvcsAgent1: PowerDemandEvcsAgent1 = min [PVInput - PowerDemandLoadAgent | RatedPowerCharging]
            EvcsAgent1 -> EV: PowerDemandEvcsAgent1
            else PVInput - PowerDemandLoadAgent < 0 -> Uncharge HomeStorage, do V2H = UnchargeEV /' SoC !> 60 '/
            HEMSAgent -> HomeStorageAgent: PowerDemandHomeStorage = min [PVInput - PowerDemandLoadAgent | RatedPowerHomeStorage] /'TODO it's not minimum should be Minimum of Absolute Value, but preserve the direction of energy flow '/
            HEMSAgent -> EvcsAgent1: PowerDemandEvcs = min [PVInput - PowerDemandLoadAgent - PowerDemandHomeStorage] | RatedPowerCharging]
            EvcsAgent1 -> EV: PowerDemandEVcs
            HEMSAgent -> HEMSAgent: New Tick @ 60% SoC EV stop unchargeEV
            HEMSAgent -> GridAgent: PowerDemandGrid = PowerDemandLoadAgent - PVInput + PowerDemandHomeStorage + PowerDemandEvcsAgent1
            deactivate EV
            end
        end
    end
    end


alt#Gold #LightBlue Trigger regular or by Changes at Load / Feed-in
    group #LightGreen Regular request
    end
    group #LightGreen Update ValueStore through trigger of Child of HEMSAgent
    end
end
@enduml



