@startuml
title Use Case Optimize Self Consumption \n Existing: LoadAgent, HomeStorage, PV \n Missing: EV
participant GridAgent
participant HEMSAgent
participant LoadAgent
participant PVAgent
participant HomeStorageAgent
group init
    GridAgent -> HEMSAgent: create()
    HEMSAgent -> LoadAgent: create()
    HEMSAgent -> PVAgent: create()
    HEMSAgent -> HomeStorageAgent: create(Volume, RatedPower, SoC)
    end
group #LightGrey firstTick
    GridAgent -> HEMSAgent: request PowerDemand
    HEMSAgent -> LoadAgent: get PowerDemand
    LoadAgent -> HEMSAgent: PowerDemand
    HEMSAgent -> PVAgent: get PVInput
    PVAgent -> HEMSAgent: PVInput
    HEMSAgent -> HomeStorageAgent: get SoC, get RatedPowerHomeStorage
    HomeStorageAgent -> HEMSAgent:  SoC, RatedPowerHomeStorage
    HEMSAgent -> HomeStorageAgent: PowerDemandHomeStorage = min [PVInput - PowerDemandLoadAgent | RatedPowerHomeStorage ]
    HEMSAgent -> GridAgent: PowerDemandGrid = PowerDemandLoadAgent - PVInput + PowerDemandHomeStorage
    end
alt#Gold #LightBlue Trigger regular or by Changes at Load / Feed-in
group #LightGreen Regular request
    GridAgent -> HEMSAgent: request PowerDemand
    HEMSAgent -> LoadAgent: get PowerDemand
    LoadAgent -> HEMSAgent: PowerDemand
    HEMSAgent -> PVAgent: get PVInput
    PVAgent -> HEMSAgent: PVInput
    HEMSAgent -> HomeStorageAgent: PowerDemandHomeStorage = min [PVInput - PowerDemandLoadAgent | RatedPowerHomeStorage ]
    HEMSAgent -> GridAgent: PowerDemandGrid = PowerDemandLoadAgent - PVInput + PowerDemandHomeStorage
    end
group #LightGreen Update ValueStore through trigger of Child of HEMSAgent
    alt Trigger by LoadAgent or PVAgent
    LoadAgent -> HEMSAgent: new PowerDemand
    else
    PVAgent -> HEMSAgent: new PVInput
    else
    HomeStorageAgent -> HEMSAgent: Soc = 1 | SoC = 0
    end
    HEMSAgent -> GridAgent: PowerDemandGrid = PowerDemandLoadAgent - PVInput + PowerDemandHomeStorage
    end
end
@enduml



