@startuml
title Use Case Optimize Self Consumption \n Existing: LoadAgent, HomeStorage, PV \n Missing: EV
group init
LoadAgent -> HEMS: PowerDemandLoadAgent
PVAgent -> HEMS: PVInput
HomeStorageAgent -> HEMS: SoC HomeStorage
end
alt#Gold #LightBlue Load <= Production
group#Gold #LightBlue Increase Load until Production
    HEMS -> HEMS: while: Load <= Production \n do increase load stepwise \n 1. while SoC HomeStorage < 1: max [(PowerPVInput - LoadAgent - PowerRatedEV) || PowerRatedHomeStorage])
    HEMS -> HomeStorageAgent: increasePower
    alt#Gold if ResidualLoad > 0
        HEMS -> GridAgent: Feed-in =  PVInput - PowerDemandLoadAgent - ChargePowerEvcsAgent1 - ChargePowerHomeStorage
        end
    end
else #Pink Load > Production
     group#Gold #LightBlue Fulfill all demands
        HEMS -> LoadAgent: No curtailment of PowerDemandLoadAgent
        HEMS -> HomeStorageAgent: while SoC HomeStorage > 0: Uncharge HomeStorage with UnchargePowerHomestorage = min [PowerDemandLoadAgent - PVInput || RatedPowerHomestorage]
        alt#Gold if ResidualLoad > 0
           HEMS -> GridAgent: PowerDemand = PowerDemandLoadAgent - UnchargePowerHomestorage - PVInput
           end
end
end



@enduml



