rules = [
  DisableSyntax,
  LeakingImplicitClassVal,
  # from scalafix-scapegoat
  ArrayEquals,
  ArraysInFormat,
  ArraysToString,
  AvoidSizeEqualsZero,
  AvoidSizeNotEqualsZero,
  AvoidToMinusOne,
  BigDecimalDoubleConstructor,
  BigDecimalScaleWithoutRoundingMode,
  BooleanParameter,
  BoundedByFinalType,
  BrokenOddness,
  CatchException,
  CatchExceptionImmediatelyRethrown,
  CatchFatal,
  CatchNpe,
  CatchThrowable,
  ClassNames,
  CollectionIndexOnNonIndexedSeq,
  CollectionNamingConfusion,
  CollectionNegativeIndex,
  CollectionPromotionToAny,
  ComparingFloatingPointTypes,
  ComparisonToEmptyList,
  ComparisonToEmptySet,
  ComparisonWithSelf,
  ConstantIf,
  DivideByOne,
  DoubleNegation,
  DuplicateImport,
  DuplicateMapKey,
  DuplicateSetValue,
  EitherGet,
  EmptyCaseClass,
  EmptyFor,
  EmptyIfBlock,
  #EmptyInterpolatedString,
  EmptyMethod,
  EmptySynchronizedBlock,
  EmptyTryBlock,
  EmptyWhileBlock,
  ExistsSimplifiableToContains,
  FilterDotHead,
  FilterDotHeadOption,
  FilterDotIsEmpty,
  FilterDotSize,
  FilterOptionAndGet,
  FinalModifierOnCaseClass,
  FinalizerWithoutSuper,
  FindAndNotEqualsNoneReplaceWithExists,
  FindDotIsDefined,
  IllegalFormatString,
  ImpossibleOptionSizeCondition,
  #IncorrectNumberOfArgsToFormat, # with this the addition of timestamps fails
  IncorrectlyNamedExceptions,
  InterpolationToString,
  InvalidRegexTest,
  #LonelySealedTrait,
  LooksLikeInterpolatedString,
  MapGetAndGetOrElse,
  MethodReturningAny,
  NanComparison,
  NullAssignment,
  NullParameter,
  OptionGet,
  OptionSize,
  RepeatedCaseBody,
  RepeatedIfElseBody,
  StripMarginOnRegex,
  SwallowedException,
  #TryGet, # was disabled in scapegoat
  UnnecessaryConversion,
  UnreachableCatch,
  UnsafeContains,
  UnsafeStringContains,
  UnsafeTraversableMethods,
  UnusedMethodParameter,
  VarCouldBeVal,
  VariableShadowing,
  WhileTrue
]

DisableSyntax {
  noWhileLoops = true
  #noIsInstanceOf = true # FIXME can be enabled once pureconfig is in use
  #noAsInstanceOf = true # FIXME same
  noXml = true
  noFinalize = true
  noValPatterns = true
}

