@startuml

start
:Determine last relevant data (schedule);
:Validate movements;
:Apply schedule to apparent cars;
note left: Each schedule is applied to\neach car apparent in that\ninstant for the time frame\nsince last movement.
:Calculate departed evs;
:Update result value store;
:Announce arrived evs to listener;
:Update relevant calculation data;

stop

@enduml
