@startuml
'https://plantuml.com/activity-diagram-beta
!theme plain

start

:Determine current time;
:Determine (non-)dispatchable evs;
note left:Evs, that need to charge with\nfull power to get filled up until\nthey depart are considered to\nbe non-dispatchable.

partition "Schedule non-dispatchable evs" {
    :Schedule to charge with full power;
}

partition "Schedule dispatchable evs" {
    :Determine all departure times;
    :Determine last departure;
    :Predict charging prices;
    :Subdivide the window based on\nprice changes and planned departures;
    :Sort evs by departure tick;
    while (evs available?)
        partition "Determine schedule for ev" {
            :Determine free capacity of battery;
            :Determine slices, where there is still power left;
            repeat :Filter slices where there is still power left;
            :Find slice with cheapest price;
            if (cheapest slice available?) then (Yes)
                :Determine needed power;
                if(needs to charge full power?) then (Yes)
                    :Block slice;
                endif
                :Update energy left to charge;
                :Add schedule entry for slice;
            else (No)
                :Throw exception;
                stop
            endif
            repeat while (ev not fully charged && charging slices left?)
            :Return schedule;
        }
    endwhile (No)
}

:Join both schedule sets;

stop

@enduml
