@startuml
'https://plantuml.com/state-diagram

' clock "Cock 0" as C0 with period 50
skinparam componentStyle rectangle

package "t0" {
    component "State (t0)" as s0
    component "OperatingPoint (t0 - ?)" as op0
        component "OperationRelevantData (t0)" as or0

}

package t1 {
    component "State (t1)" as s1
}

package t2 {
    component "State (t2)" as s2
}


s0 -> op0
or0 -> op0

s0 -> s1
op0 -> s1

s1 -> s2

' Layouting:
s0 -[hidden]-> or0
'States --> OperatingPoints

@enduml