@startuml

== Phase 1 ==
Mosaik -> SIMOSAIK: ! Activation(tick)
SIMOSAIK -> SIMONA: StateData(currentTick = Some(tick))

activate SIMOSAIK

SIMOSAIK -> SIMOSAIK: DoSomething()

deactivate SIMOSAIK

SIMOSAIK -> Mosaik: ! Completion(tick)

@enduml