@startuml

!theme plain

==Init==
SimScheduler -> ExtSimAdapter: <font color=red>!</font> InitializeExtSimAdapterTrigger(InitExtSimAdapterData)
activate ExtSimAdapter

ExtSimAdapter -> SimScheduler: <font color=red>!</font> CompletionMessage(InitTick)
deactivate ExtSimAdapter



SimScheduler -> ExtSimAdapter: <font color=red>!</font> ActivityStartTrigger(-1L)
activate ExtSimAdapter

ExtSimAdapter -> ExtSimulation: queue(ExtActivityStartTrigger(-1L))
activate ExtSimulation

ExtSimulation -> ExtDcopfSim: initialize()

ExtSimulation -> ExtSimAdapter: queue(CompletionMessage(newTriggers))
deactivate ExtSimulation

ExtSimAdapter -> SimScheduler: <font color=red>!</font> CompletionMessage(newTriggers)
deactivate ExtSimAdapter



SimScheduler -> PrimaryServiceProxy: <font color=red>!</font> ScheduleServiceTrigger(InitializeServiceTrigger(-1L))
activate PrimaryServiceProxy

SimScheduler -> ExtOpfDataService: <font color=red>!</font> ScheduleServiceTrigger(InitializeServiceTrigger(-1L))
activate ExtOpfDataService

ExtOpfDataService -> PrimaryServiceProxy: <font color=red>!</font> ExtOpfRegistrationMessage(generators)
ExtOpfDataService -> SimScheduler: <font color=red>!</font> CompletionMessage(GeneratorDataRef)
deactivate ExtOpfDataService

SimScheduler -> Generator1: <font color=red>!</font> ActivityStartTrigger(-1L)
activate Generator1
SimScheduler -> Generator2: <font color=red>!</font> ActivityStartTrigger(-1L)
activate Generator2

Generator1 -> PrimaryServiceProxy: <font color=red>!</font> PrimaryServiceRegistrationMessage
Generator2 -> PrimaryServiceProxy: <font color=red>!</font> PrimaryServiceRegistrationMessage

PrimaryServiceProxy -> Generator1: <font color=red>!</font> WorkerRegistrationMessage + <font color=red>!</font> RegistrationSuccessfulMessage
PrimaryServiceProxy -> Generator2: <font color=red>!</font> WorkerRegistrationMessage + <font color=red>!</font> RegistrationSuccessfulMessage
PrimaryServiceProxy -> SimScheduler: <font color=red>!</font> CompletionMessage(None)
deactivate PrimaryServiceProxy

Generator1 -> SimScheduler: <font color=red>!</font> CompletionMessage(None)
deactivate Generator1
Generator2 -> SimScheduler: <font color=red>!</font> CompletionMessage(None)
deactivate Generator2

==Sim==
SimScheduler -> ExtSimAdapter: <font color=red>!</font> ActivityStartTrigger(tick)
activate ExtSimAdapter

ExtSimAdapter -> ExtSimulation: queue(ExtActivityStartTrigger(tick))
deactivate ExtSimAdapter

activate ExtSimulation
ExtSimulation -> ExtDcopfSim: doActivity(tick)
activate ExtDcopfSim
ExtDcopfSim -> ExtSimulation: sendSetpoints(opfData)
deactivate ExtDcopfSim

ExtSimulation -> ExtOpfDataService: <font color=red>!</font> ExtOpfMessage(_)
ExtSimulation -> ExtSimAdapter: <font color=red>!</font> ScheduleDataServiceMessage(\n\tdataServiceRef)
deactivate ExtSimulation

activate ExtSimAdapter
ExtSimAdapter -> SimScheduler: <font color=red>!</font> ScheduleTriggerMessage(_, dataServiceRef)
deactivate ExtSimAdapter

SimScheduler -> ExtOpfDataService: <font color=red>!</font> ActivityStartTrigger(tick)
activate ExtOpfDataService
ExtOpfDataService -> Generator1: <font color=red>!</font> ProvideSetpointsMessage(_)
ExtOpfDataService -> Generator2: <font color=red>!</font> ProvideSetpointsMessage(_)
ExtOpfDataService -> ExtSimAdapter: <font color=red>!</font> CompletionMessage(newTriggers)
deactivate ExtOpfDataService
activate ExtSimAdapter
ExtSimAdapter -> SimScheduler: <font color=red>!</font> CompletionMessage(newTriggers)
deactivate ExtSimAdapter


SimScheduler -> Generator1: <font color=red>!</font> ActivityStartTrigger(tick)
activate Generator1
SimScheduler -> Generator2: <font color=red>!</font> ActivityStartTrigger(tick)
activate Generator2
Generator1 -> SimScheduler: <font color=red>!</font> CompletionMessage(None)
deactivate Generator1
Generator2 -> SimScheduler: <font color=red>!</font> CompletionMessage(None)
deactivate Generator2

@enduml