@startuml
SimonaSim -> Listener: create()
SimonaSim -> Scheduler: create()
SimonaSim -> Services: create()
SimonaSim -> Scheduler: <font color=red>!</font> ScheduleActivation(\n\tInitializeServiceTrigger(0),\n\tweatherActorRef)
SimonaSim -> GridAgents: create()
SimonaSim -> Scheduler: <font color=red>!</font> ScheduleActivation(\n\tInitializeGridAgentTrigger(0),\n\tgridAgentInitData,\n\tgridAgentRef)
SimonaSim -> Scheduler: <font color=red>?</font> StartScheduleMessage()
Scheduler -> Services: <font color=red>!</font> TriggerWithIdMessage(\n\tInitializeServiceTrigger(_),\n\ttriggerId,\n\t_)
Services --> Scheduler: <font color=red>!</font> Completion(\n\ttriggerId,\n\tScheduleActivation[...])
Scheduler -> GridAgents: <font color=red>!</font> TriggerWithIdMessage(\n\tInitializeGridAgentTrigger(_),\n\ttriggerId,\n\t_)
GridAgents -> Scheduler: <font color=red>!</font> ScheduleActivation(\n\tInitializeSystemComponentsTrigger(0),\n\tassetAgentRef)
GridAgents --> Scheduler: <font color=red>!</font> Completion(triggerId, ScheduleActivation[...])
Scheduler -> ParticipantAgents: <font color=red>!</font> TriggerWithIdMessage(\n\tIInitializeSystemComponentsTrigger(_),\n\ttriggerId,\n\t_)
ParticipantAgents -> Services: <font color=red>!</font> RegisterForWeatherMessage(lat, lon)
ParticipantAgents -> Services: <font color=red>!</font> RegisterFor...
Services --> ParticipantAgents: <font color=red>!</font> RegistrationResponseMessages
ParticipantAgents --> Scheduler: <font color=red>!</font> Completion(\n\ttriggerId,\n\tScheduleActivation[\n\t\tActivation(tick)\n\t])
@enduml