@startuml
Scheduler -> ParticipantAgents: <font color=red>!</font> TriggerWithIdMessage(\n\tIInitializeSystemComponentsTrigger(_),\n\ttriggerId,\n\t_)
ParticipantAgents --> Scheduler: <font color=red>!</font> Completion(triggerId, ScheduleActivation[...])
Scheduler -> ParticipantAgents: <font color=red>!</font> TriggerWithIdMessage(\n\tActivation(tick),\n\t_,\n\t_)
ParticipantAgents --> Scheduler: <font color=red>!</font> Completion(triggerId, None)
@enduml