consider_load_shifting: False
simulate_typical_days: False  
switch_on_probabilities_datapath: tests/input/switch_on_probabilities
usage_probabilities_file: tests/input/usage_probabilities/usage_probabilities.csv

