# © 2024. TU Dortmund University,
# Institute of Energy Systems, Energy Efficiency and Energy Economics,
# Research group Distribution grid planning and operation
#

name: CI

on:
  push:
    branches:
      - main
      - dev
      - 'feature/*'
      - 'hotfix/*'
      - 'release/*'
  pull_request:
    branches:
      - main
      - dev

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # Check if it's a pull request
          ref: ${{ github.event.pull_request.head.ref || github.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Show current branch
        run: |
          git rev-parse --abbrev-ref HEAD

  build:
    runs-on: ubuntu-latest
    container:
      image: amazoncorretto:17
      options: --user root

    steps:
      # Install Gradle 8.10
      - name: Install Gradle 8.10
        shell: bash
        run: |
          yum update -y
          yum install -y wget unzip
          GRADLE_VERSION=8.10
          wget https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip -P /tmp
          unzip /tmp/gradle-${GRADLE_VERSION}-bin.zip -d /opt/gradle
          rm /tmp/gradle-${GRADLE_VERSION}-bin.zip
          echo "GRADLE_HOME=/opt/gradle/gradle-${GRADLE_VERSION}" >> $GITHUB_ENV
          echo "PATH=\$GRADLE_HOME/bin:\$PATH" >> $GITHUB_ENV

      # Verify Gradle and Java installation
      - name: Verify Gradle & Java version
        shell: bash
        run:
          gradle -v && java -v