# © 2024. TU Dortmund University,
# Institute of Energy Systems, Energy Efficiency and Energy Economics,
# Research group Distribution grid planning and operation
#

name: CI

on:
  push:
    paths-ignore:
      - 'docs/**'
    branches:
      - main
      - dev
      - 'hotfix/*'
      - 'rel/*'
      - 'dependabot/*'
  pull_request:
    branches:
      - main
      - dev

jobs:
  buildAndTest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Check Branch
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            branch_name="${{ github.head_ref }}"
          else
            branch_name="${{ github.ref_name }}"
          fi

          if [[ "$branch_name" == refs/heads/* ]]; then
            branch_name="${branch_name#refs/heads/}"
          fi
          
          export branch_name
          
          echo "branch_name=$branch_name" >> $GITHUB_ENV
          
          ./gradlew checkBranchName -PbranchName="$branch_name"
          
          bash scripts/branch_type.sh

      - name: Get Versions
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          REPO_URL=$(git config --get remote.origin.url)
          echo "REPO_URL=$REPO_URL" >> $GITHUB_ENV
          bash scripts/get_versions.sh

      - name: Version Check
        if: ${{ github.event_name == 'pull_request' }}
        env:
          BASE_BRANCH: ${{ github.event.pull_request.base.ref }}
        run: bash scripts/version_check.sh

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Build Project
        run: ./gradlew --refresh-dependencies clean assemble spotlessCheck

      - name: Run Tests
        run: ./gradlew test reportScoverage checkScoverage

      - name: Build Scala-Docs
        run: ./gradlew scaladoc

      - name: SonarQube
        run: |
          ./gradlew sonar \
          -Dsonar.projectKey=${{ vars.SONAR_PROJECT_KEY }} \
          -Dsonar.host.url=${{ vars.SONAR_HOST_URL }} \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
          -Dsonar.qualitygate.wait=true

      #Deployment
      - name: Deploy
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev'
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.MAVENCENTRAL_SIGNINGKEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.MAVENCENTRAL_SIGNINGPASS }}
          ORG_GRADLE_PROJECT_user: ${{ secrets.MAVENCENTRAL_USER }}
          ORG_GRADLE_PROJECT_password: ${{ secrets.MAVENCENTRAL_PASS }}
        run: |
          if [ "${GITHUB_REF}" == "refs/heads/main" ]; then
            currentVersion=$(./gradlew -q currentVersion)
          else
            currentVersion=$(./gradlew -q devVersion)
          fi
          
          echo "currentVersion=$currentVersion"

          ./gradlew publish -PdeployVersion=$currentVersion
