# © 2024. TU Dortmund University,
# Institute of Energy Systems, Energy Efficiency and Energy Economics,
# Research group Distribution grid planning and operation
#

name: CI

on:
  push:
    branches:
      - main
      - dev
      - 'feature/*'
      - 'hotfix/*'
      - 'release/*'
  pull_request:
    branches:
      - main
      - dev

jobs:

  build:
    runs-on: ubuntu-latest
    container:
      image: gradle:8.10-jdk17

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref || github.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}

      - name: Check Branch & Files
        run: |
          git config --global --add safe.directory /__w/simona/simona
          git rev-parse --abbrev-ref HEAD
          pwd
          ls -la

      - name: Checking Gradle & Java
        run: |
          java -version && gradle --version

      - name: Building Project
        run: |
          ./gradlew clean assemble
          ls -la

      - name: Cache Gradle Wrapper and Build Files
        uses: actions/cache@v3
        with:
          path: |
            ./build/
            ./gradle/
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

  test:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: gradle:8.10-jdk17
    services:
      docker:
        image: docker:19.03.12
        options: --privileged

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref || github.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}

      - name: Cache Gradle Wrapper and Build Files
        uses: actions/cache@v3
        with:
          path: |
            ./build/
            ./gradle/wrapper/
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Running Tests
        run: |
          ./gradlew --no-daemon --info --refresh-dependencies spotlessCheck pmdMain pmdTest test

      - name: Generate JavaDoc
        run: |
          ./gradlew javadoc
