# © 2024. TU Dortmund University,
# Institute of Energy Systems, Energy Efficiency and Energy Economics,
# Research group Distribution grid planning and operation
#

name: CI

on:
  push:
    paths-ignore:
      - 'docs/**'
    branches:
      - main
      - dev
      - 'hotfix/*'
      - 'rel/*'
      - 'dependabot/*'
  pull_request:
    branches:
      - main
      - dev

jobs:
  buildAndTest:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout Source
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Check Branch
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            BRANCH_NAME="${{ github.head_ref }}"
          else
            BRANCH_NAME="${{ github.ref_name }}"
          fi

          if [[ "$BRANCH_NAME" == refs/heads/* ]]; then
            BRANCH_NAME="${BRANCH_NAME#refs/heads/}"
          fi
          
          export BRANCH_NAME
          
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          
          ./gradlew checkBranchName -PbranchName="$BRANCH_NAME" --warning-mode=none
          
          bash scripts/branch_type.sh

      - name: Version Check
        if: ${{ github.event_name == 'pull_request' }}
        env:
          BASE_BRANCH: ${{ github.event.pull_request.base.ref }}
        run: bash scripts/run-version-check.sh

      - name: Build Project
        run: ./gradlew --refresh-dependencies clean assemble spotlessCheck

      - name: Run Tests
        run: ./gradlew test reportScoverage checkScoverage

      - name: Build Scala-Docs
        run: ./gradlew scaladoc

      - name: SonarQube
        run: |
          ./gradlew sonar \
          -Dsonar.projectKey=${{ vars.SONAR_PROJECT_KEY }} \
          -Dsonar.host.url=${{ vars.SONAR_HOST_URL }} \
          -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
          -Dsonar.qualitygate.wait=true

      #Deployment
      - name: Deploy
        if: github.ref == 'refs/heads/main'
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.MAVENCENTRAL_SIGNINGKEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.MAVENCENTRAL_SIGNINGPASS }}
          ORG_GRADLE_PROJECT_mavenCentralUser: ${{ github.actor == 'sebastian-peter' && secrets.MAVENCENTRAL_USER ||
            github.actor == 'danielfeismann' && secrets.MAVENCENTRAL_DANIEL_USER || github.actor == 'staudtMarius' && secrets.MAVENCENTRAL_MARIUS_USER }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ github.actor == 'sebastian-peter' && secrets.MAVENCENTRAL_PASS ||
            github.actor == 'danielfeismann' && secrets.MAVENCENTRAL_DANIEL_PASS || github.actor == 'staudtMarius' && secrets.MAVENCENTRAL_MARIUS_PASS }}

        run: |
          echo "Using MavenCentral Token of GitHub Actor: ${{ github.actor }}"
          currentVersion=$(./gradlew -q currentVersion)

          echo "currentVersion=$currentVersion"

          ./gradlew publish -PdeployVersion=$currentVersion


      #MavenCentral Staging
      - name: MavenCentral Staging
        if: github.ref == 'refs/heads/main'
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.MAVENCENTRAL_SIGNINGKEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.MAVENCENTRAL_SIGNINGPASS }}
          ORG_GRADLE_PROJECT_mavenCentralUser: ${{ github.actor == 'sebastian-peter' && secrets.MAVENCENTRAL_USER ||
            github.actor == 'danielfeismann' && secrets.MAVENCENTRAL_DANIEL_USER || github.actor == 'staudtMarius' && secrets.MAVENCENTRAL_MARIUS_USER }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ github.actor == 'sebastian-peter' && secrets.MAVENCENTRAL_PASS ||
            github.actor == 'danielfeismann' && secrets.MAVENCENTRAL_DANIEL_PASS || github.actor == 'staudtMarius' && secrets.MAVENCENTRAL_MARIUS_PASS }}

        run: |
          ./gradlew stagingAtMavenCentralPortal
