# © 2024. TU Dortmund University,
# Institute of Energy Systems, Energy Efficiency and Energy Economics,
# Research group Distribution grid planning and operation
#

name: CI

#Variables
env:
  CHECKOUT_SHA: ""

on:
  push:
    branches:
      - main
      - dev
      - 'feature/*'
      - 'hotfix/*'
      - 'release/*'
  pull_request:
    branches:
      - main
      - dev

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # Check if it's a pull request
          ref: ${{ github.event.pull_request.head.ref || github.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}

      - name: Check Branch & Files
        run: |
          git rev-parse --abbrev-ref HEAD
          pwd
          ls -la

      - name: Cache project files
        uses: actions/cache@v3
        id: cache
        with:
          path: |
            . #Cache all files
          key: simona-${{ github.sha }}

      - name: Save Commit SHA
        run: |
          echo "COMMIT_SHA=${GITHUB_SHA}" >> $GITHUB_ENV 
          echo "${{ github.sha }}"

  build:
    needs: checkout
    runs-on: ubuntu-latest
    container:
      image: gradle:8.10-jdk17

    steps:
      - name: Print SHA
        run: echo "${{ github.sha }}"

      - name: Restore project files
        uses: actions/cache/restore@v4
        id: restore-cache
        with:
          path: ./
          key: simona-${{ github.sha }}

      - name: Checking Gradle & Java
        run: |
          java -version && gradle --version

      - name: Building Project
        run: |
          pwd
          ls -la
          gradle clean assemble

  test:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: gradle:8.10-jdk17
      options: --user root
      volumes:
        - ${{ github.workspace }}:/simona:rw

    steps:
      - name: Checking Gradle & Java
        run: |
          java -version && gradle --version

      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: simona-3.1.0-all.jar

      - name: Running tests
        run: |
          gradle --refresh-dependencies spotlessCheck pmdMain pmdTest

      - name: Generate JavaDoc
        run: |
          set +x
          cd simona
          ./gradlew javadoc
