# © 2024. TU Dortmund University,
# Institute of Energy Systems, Energy Efficiency and Energy Economics,
# Research group Distribution grid planning and operation
#

name: CI

on:
  push:
    branches:
      - main
      - dev
      - 'feature/*'
      - 'hotfix/*'
      - 'release/*'
  pull_request:
    branches:
      - main
      - dev

jobs:
  checkout_code:
    runs-on: ubuntu-latest
    steps:
      - name: Test SSH Key Authorization
        if: secrets.SSH_PRIVATE_KEY
        run: ssh -T git@github.com || echo "SSH key not authorized"
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # Check if it's a pull request
          ref: ${{ github.event.pull_request.head.ref || github.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Show current branch
        run: |
          git rev-parse --abbrev-ref HEAD