# © 2024. TU Dortmund University,
# Institute of Energy Systems, Energy Efficiency and Energy Economics,
# Research group Distribution grid planning and operation
#

name: CI

#Variables
env:
  CHECKOUT_SHA: ""

on:
  push:
    branches:
      - main
      - dev
      - 'feature/*'
      - 'hotfix/*'
      - 'release/*'
  pull_request:
    branches:
      - main
      - dev

jobs:

  build:
    runs-on: ubuntu-latest
    container:
      image: gradle:8.10-jdk17

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # Check if it's a pull request
          ref: ${{ github.event.pull_request.head.ref || github.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}

      - name: Check Branch & Files
        run: |
          git rev-parse --abbrev-ref HEAD
          pwd
          ls -la

      - name: Checking Gradle & Java
        run: |
          java -version && gradle --version

      - name: Building Project
        run: |
          gradle clean assemble

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: simona-build
          path: |
            build/                  # Der gesamte 'build'-Ordner
            build.gradle            # Haupt-Gradle-Datei
            settings.gradle         # Projekt- und Modulkonfiguration
            gradle/wrapper/         # Gradle-Wrapper-Dateien
            .gradle/                # Cache-Dateien von Gradle (optional)

  test:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: gradle:8.10-jdk17

    steps:
      - name: Checking Gradle & Java
        run: |
          java -version && gradle --version

      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: simona-build

      - name: Running tests
        run: |
          gradle --refresh-dependencies spotlessCheck pmdMain pmdTest

      - name: Generate JavaDoc
        run: |
          set +x
          cd simona
          ./gradlew javadoc
